sudo: required
language: node_js
node_js:
  - "6"
before_install:
  - rm -rf node_modules
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run test
after_success:
  - bash <(curl -s https://codecov.io/bash)